=== AlfVII/mal/schemas/wire/material.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "wire/material",
    "description": "A material for wire",
    "type": "object",
    "properties": {
        "name": {   
            "description": "The name of a wire material",
            "type": "string"
        },
        "permeability":{
            "description": "The permeability of a wire material",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "resistivity":{"$ref": "#/$defs/resistivity"},
        "thermalConductivity":{
            "type": "array",
            "items": {
                "$ref": "#/$defs/thermalConductivityPoint"
            },
            "minItems": 1
        }
    },
    "required": ["name", "permeability", "resistivity"],

    "$defs": {
        "resistivity": {
            "description": "data for describing the resistivity of a wire",
            "type": "object",
            "properties": {
                "referenceValue": {
                    "description": "Resistivity reference value, in Ohm * m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "referenceTemperature": {
                    "description": "Temperature reference value, in Celsius",
                    "type": "number"
                },
                "temperatureCoefficient": {
                    "description": "Temperature coefficient value, alpha, in 1 / Celsius",
                    "type": "number"
                }
            },
            "required": ["referenceValue", "referenceTemperature", "temperatureCoefficient"]
        },
        "thermalConductivityPoint": {
            "description": "data for describing one point of thermal conductivity",
            "type": "object",
            "properties": {
                "value": {
                    "description": "Thermal conductivity value, in W / m * K",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "temperature": {
                    "description": "Temperature for the field value, in Celsius",
                    "type": "number"
                }
            },
            "required": ["value", "temperature"]
        }
    }
}

=== AlfVII/mal/samples/magnetic/wire/material/copper.json
{
    "name": "copper",
    "permeability": 0.999994,
    "resistivity": {
        "referenceValue": 1.678e-08,
        "referenceTemperature": 20.0,
        "temperatureCoefficient": 0.004041
    },
    "thermalConductivity": [
        {
            "value": 413,
            "temperature": -73
        },
        {
            "value": 401,
            "temperature": 0
        },
        {
            "value": 392,
            "temperature": 127
        },
        {
            "value": 383,
            "temperature": 327
        },
        {
            "value": 371,
            "temperature": 527
        },
        {
            "value": 357,
            "temperature": 727
        },
        {
            "value": 342,
            "temperature": 927
        }
    ]
}
