=== AlfVII/mal/schemas/wire/solid.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "resource:/schemas/wire/solid#",
    "title": "wire/solid",
    "description": "The description of a solid magnet wire",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of wire",
            "type": "string"
        },
        "type": {
            "description": "The type of wire",
            "type": "string",
            "enum": ["round", "rectangular", "foil"]
        },
        "standard": {
            "description": "The standard of wire",
            "type": "string",
            "enum": ["IEC 60317", "JIS C3202", "NEMA MW 1000C"]
        },
        "manufacturer": {
            "description": "The manufacturer of the wire",
            "type": "string"
        },
        "manufacturerPartNumber": {
            "description": "The part number of manufacturer for the wire",
            "type": "string"
        },
        "material": {
            "oneOf": [
                {"$ref": "file://schemas/wire/material.json"},
                {
                    "description": "The name of the material used in the wire",
                    "type": "string"
                }
            ]
        },
        "conductingDiameter": {
            "description": "The conducting diameter of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "conductingWidth": {
            "description": "The conducting width of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "conductingHeight": {
            "description": "The conducting height of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "conductingThickness": {
            "description": "The conducting thickness of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "numberConductors": {
            "description": "The number of conductors in the wire",
            "type": "number",
            "const": 1
        },
        "outerDiameter": {
            "description": "The outer diameter of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "outerWidth": {
            "description": "The outer width of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "outerHeight": {
            "description": "The outer height of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "outerThickness": {
            "description": "The outer thickness of the wire, in m",
            "$ref": "#/$defs/dimensionWithTolerance"
        },
        "coating": {
            "oneOf": [
                {"$ref": "file://schemas/insulation/wireCoating.json"},
                {
                    "description": "The name of the coating used in the wire",
                    "type": "string"
                }
            ]
        }
    },
    "allOf": [
        {
            "if": {
                "properties": { "type": { "const": "round" } }
            },
            "then": {
                "required": ["type", "material", "conductingDiameter", "outerDiameter", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "outerWidth" ] },
                        { "required": [ "outerHeight" ] },
                        { "required": [ "outerThickness" ] },
                        { "required": [ "conductingWidth" ] },
                        { "required": [ "conductingHeight" ] },
                        { "required": [ "conductingThickness" ] }
                    ]
                }
            }
        },
        {
            "if": {
                "properties": { "type": { "const": "rectangular" } }
            },
            "then": {
                "required": ["type", "material", "conductingWidth", "outerWidth", "conductingThickness", "outerThickness", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "conductingHeight" ] },
                        { "required": [ "conductingDiameter" ] },
                        { "required": [ "outerHeight" ] },
                        { "required": [ "outerDiameter" ] }
                    ]
                }
            }
        },
        {
            "if": {
                "properties": { "type": { "const": "foil" } }
            },
            "then": {
                "required": ["type", "material", "conductingThickness", "outerThickness", "conductingHeight", "outerHeight", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "conductingWidth" ] },
                        { "required": [ "outerWidth" ] },
                        { "required": [ "conductingDiameter" ] },
                        { "required": [ "outerDiameter" ] }
                    ]
                }
            }
        }
    ],

    "$defs": {
        "dimensionWithTolerance": {
            "description": "A dimension of the wire, in m",
            "type": "object",
            "properties": {
                "minimum": {
                    "description": "The minimum value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "nominal": {
                    "description": "The nominal value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "maximum": {
                    "description": "The maximum value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                }
            },
            "anyOf": [
                {"required": ["nominal"]},
                {"required": ["maximum"]}
            ]
        }
    }
}

=== AlfVII/mal/samples/magnetic/wire/solid/rectangular_0.0014_0.004.json
{
    "type": "rectangular",
    "material": "copper",
    "numberConductors": 1,
    "conductingWidth": {
        "minimum": 0.00393,
        "nominal": 0.004,
        "maximum": 0.00407
    },
    "conductingThickness": {
        "minimum": 0.00135,
        "nominal": 0.0014,
        "maximum": 0.00145
    },
    "outerWidth": {
        "nominal": 0.00405
    },
    "outerThickness": {
        "minimum": 0.00138,
        "maximum": 0.00161
    },
    "coating":{
        "type": "enamelled",
        "maximumThickness": 0.00016,
        "grade": 1,
        "breakdownVoltage": 1600
    }
}

=== AlfVII/mal/samples/magnetic/wire/solid/foil_0.02_0.0001.json
{
    "type": "foil",
    "material": "copper",
    "numberConductors": 1,
    "conductingHeight": {
        "minimum": 0.0193,
        "nominal": 0.02,
        "maximum": 0.0207
    },
    "conductingThickness": {
        "nominal": 0.0001
    },
    "outerHeight": {
        "minimum": 0.0193,
        "nominal": 0.02,
        "maximum": 0.0207
    },
    "outerThickness": {
        "minimum": 0.00009,
        "maximum": 0.00011
    },
    "coating":{
        "type": "enamelled",
        "maximumThickness": 0.00016,
        "grade": 1,
        "breakdownVoltage": 1600
    }
}
