=== AlfVII/mal/schemas/wire/stranded.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "resource:/schemas/wire/strand#",
    "title": "wire/strand",
    "description": "The description of a strand magnet wire",
    "type": "object",
    "properties": {
        "type": {
            "description": "The type of wire",
            "type": "string",
            "const": "litz"
        },
        "standard": {
            "description": "The standard of wire",
            "type": "string",
            "enum": ["IEC 60317", "JIS C3202", "NEMA MW 1000C"]
        },
        "manufacturer": {
            "description": "The manufacturer of the wire",
            "type": "string"
        },
        "manufacturerPartNumber": {
            "description": "The part number of manufacturer for the wire",
            "type": "string"
        },
        "strand": {
            "description": "The wire used as strands",
            "oneOf": [
                {"$ref": "file://schemas/wire/solid.json"},
                {
                    "description": "The name of the wire used as strand",
                    "type": "string"
                }
            ]
        },
        "numberConductors": {
            "description": "The number of conductors in the wire",
            "type": "number",
            "exclusiveMinimum": 1
        },
        "outerDiameter": {
            "description": "The outer diameter of the wire, in m",
            "$ref": "#/$defs/dimension"
        },
        "coating": {
            "oneOf": [
                {"$ref": "file://schemas/insulation/wireCoating.json"},
                {
                    "description": "The name of the coating used in the wire",
                    "type": "string"
                }
            ]
        }
    },
    "required": ["type", "strand", "numberConductors", "outerDiameter", "coating"],

    "$defs": {
        "dimension": {
            "description": "A dimension of the wire, in m",
            "type": "object",
            "properties": {
                "minimum": {
                    "description": "The minimum value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "nominal": {
                    "description": "The nominal value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "maximum": {
                    "description": "The maximum value of the dimension, in m",
                    "type": "number",
                    "exclusiveMinimum": 0
                    }
                },
            "anyOf": [
                {"required": ["nominal"]},
                {"required": ["maximum"]}
            ]
        }
    }
}

=== AlfVII/mal/samples/wire/stranded/Litz_20x0.8.json
{
    "type": "litz",
    "numberConductors": 20,
    "manufacturer": "Elektrisola",
    "strand": {
        "type": "round",
        "material": "copper",
        "numberConductors": 1,
        "conductingDiameter": {
            "nominal": 0.00008
        },
        "outerDiameter": {
            "minimum": 0.000095,
            "maximum": 0.000101
        },
        "coating":{
            "type": "enamelled",
            "maximumThickness": 0.0000105,
            "grade": 2,
            "breakdownVoltage": 850
        }
    },
    "outerDiameter": {
        "minimum": 0.540,
        "maximum": 0.574
    },
    "coating": {
        "type": "served",
        "serving": "single"
    }
}

=== AlfVII/mal/samples/magnetic/wire/stranded/TXXL550_44FXXX-2(MWXX).json
{
    "type": "litz",
    "numberConductors": 550,
    "manufacturer": "Rubadue",
    "manufacturerPartNumber": "TXXL550/44FXXX-3(MWXX)",
    "strand": {
        "type": "round",
        "material": "copper",
        "numberConductors": 1,
        "conductingDiameter": {
            "nominal": 5.08e-5
        },
        "outerDiameter": {
            "nominal": 6.35e-5
        },
        "coating":{
            "type": "enamelled",
            "maximumThickness": 2.54e-6,
            "grade": 1,
            "breakdownVoltage": 1600
        }
    },
    "outerDiameter": {
        "maximum": 0.00220726
    },
    "coating": {
        "type": "insulated",
        "material": {
            "composition": "teflon",
            "name": "FEP",
            "manufacturer": "Rubadue",
            "dielectricStrength":[
                {
                    "value": 260e6,
                    "thickness": 0.0000254
                },
                {
                    "value": 70e6,
                    "thickness": 0.005
                }
            ],
            "rating": {
                "temperature": 155,
                "voltage": 1000
            }
        },
        "numberLayers": 3,
        "thicknessLayers": 7.62e-5
    }
}
