=== AlfVII/mal/schemas/magnetic/wire/solid.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "http://openmagnetics.com/schemas/magnetic/wire/solid.json",
    "title": "wire/solid",
    "description": "The description of a solid magnet wire",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of wire",
            "type": "string"
        },
        "type": {
            "description": "The type of wire",
            "type": "string",
            "enum": ["round", "rectangular", "foil"]
        },
        "standard": {
            "description": "The standard of wire",
            "title": "wireStandard",
            "type": "string",
            "enum": ["IEC 60317", "JIS C3202", "NEMA MW 1000 C"]
        },
        "standardName": {
            "description": "Name according to the standard of wire",
            "type": "string"
        },
        "manufacturerInfo": {
            "$ref": "/schemas/utils.json#/$defs/manufacturerInfo"
        },
        "material": {
            "title": "WireMaterialDataOrNameUnion",
            "oneOf": [
                {"$ref": "/schemas/magnetic/wire/material.json"},
                {
                    "description": "The name of the material used in the wire",
                    "type": "string"
                }
            ]
        },
        "conductingDiameter": {
            "description": "The conducting diameter of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "conductingWidth": {
            "description": "The conducting width of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "conductingHeight": {
            "description": "The conducting height of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "numberConductors": {
            "description": "The number of conductors in the wire",
            "type": "integer",
            "const": 1
        },
        "outerDiameter": {
            "description": "The outer diameter of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "outerWidth": {
            "description": "The outer width of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "outerHeight": {
            "description": "The outer height of the wire, in m",
            "$ref": "/schemas/utils.json#/$defs/dimensionWithTolerance"
        },
        "coating": {
            "title": "CoatingDataOrNameUnion",
            "oneOf": [
                {"$ref": "/schemas/magnetic/insulation/wireCoating.json"},
                {
                    "description": "The name of the coating used in the wire",
                    "type": "string"
                }
            ]
        }
    },
    "allOf": [
        {
            "if": {
                "properties": { "type": { "const": "round" } }
            },
            "then": {
                "required": ["type", "material", "conductingDiameter", "outerDiameter", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "outerWidth" ] },
                        { "required": [ "outerHeight" ] },
                        { "required": [ "conductingWidth" ] },
                        { "required": [ "conductingHeight" ] }
                    ]
                }
            }
        },
        {
            "if": {
                "properties": { "type": { "const": "rectangular" } }
            },
            "then": {
                "required": ["type", "material", "conductingWidth", "outerWidth", "conductingHeight", "outerHeight", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "conductingDiameter" ] },
                        { "required": [ "outerDiameter" ] }
                    ]
                }
            }
        },
        {
            "if": {
                "properties": { "type": { "const": "foil" } }
            },
            "then": {
                "required": ["type", "material", "conductingWidth", "outerWidth", "conductingHeight", "outerHeight", "coating"],
                 "not": {
                    "anyOf": [
                        { "required": [ "conductingDiameter" ] },
                        { "required": [ "outerDiameter" ] }
                    ]
                }
            }
        }
    ],

    "$defs": {
    }
}

=== AlfVII/mal/samples/wire/solid/D29A01TXX-1.5.json
{
    "type": "round",
    "material": "copper",
    "numberConductors": 1,
    "conductingDiameter": {
        "nominal": 0.000287
    },
    "outerDiameter": {
        "maximum": 0.000439
    },
    "coating": {
        "type": "insulated",
        "material": {
            "composition": "teflon",
            "name": "Tefzel ETFE",
            "manufacturer": "Dupont",
            "manufacturerPartNumber": "D29A01TXX-1.5",
            "dielectricStrength":[
                {
                    "value": 1800,
                    "thickness": 0.003175
                }
            ],
            "rating": {
                "temperature": 180,
                "voltage": 600
            }
        },
        "numberLayers": 2,
        "thicknessLayers": 3.81e-5,
        "breakdownVoltage": 4500
    }
}

=== AlfVII/mal/samples/magnetic/wire/solid/0.000140.json
{
    "type": "round",
    "material": "copper",
    "numberConductors": 1,
    "conductingDiameter": {
        "nominal": 0.000140
    },
    "outerDiameter": {
        "minimum": 0.000151,
        "maximum": 0.000160
    },
    "coating":{
        "type": "enamelled",
        "thickness": {
            "maximum": 0.00002
        },
        "grade": 1,
        "breakdownVoltage": 1600
    }
}

=== AlfVII/mal/samples/magnetic/wire/rectangular/rectangular_0.0014_0.004.json
{
    "type": "rectangular",
    "material": "copper",
    "numberConductors": 1,
    "conductingHeight": {
        "minimum": 0.00393,
        "nominal": 0.004,
        "maximum": 0.00407
    },
    "conductingWidth": {
        "minimum": 0.00135,
        "nominal": 0.0014,
        "maximum": 0.00145
    },
    "outerHeight": {
        "nominal": 0.00405
    },
    "outerWidth": {
        "minimum": 0.00138,
        "maximum": 0.00161
    },
    "coating":{
        "type": "enamelled",
        "thickness": {
            "maximum": 0.00016
        },
        "grade": 1,
        "breakdownVoltage": 1600
    }
}
