=== AlfVII/mal/schemas/insulation/material.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "insulation/material",
    "$id": "http://openmagnetics.com/schemas/insulation/material.json",
    "description": "A material for insulation",
    "type": "object",
    "properties": {
        "composition": {
            "description": "The composition of a insulation material",
            "type": "string",
            "enum": ["polyimide", "bakelite", "nylon", "paper", "polystyrene", "teflon", "air"]
        },
        "name": {
            "description": "The name of a insulation material",
            "type": "string"
        },
        "manufacturer": {
            "description": "The manufacturer of the insulation material",
            "type": "string"
        },
        "dielectricStrength":{
            "type": "array",
            "items": {
                "$ref": "#/$defs/dieletricStrengthPoint"
            },
            "minItems": 1
        },
        "thermalConductivity": {
            "description": "The thermal conductivity of the insulation material, in W / m * K",
            "type": "number",
            "exclusiveMinimum": 0
        },
        "rating": {
            "description": "The rating of the material",
            "type": "object",
            "properties": {
                "temperature": {
                    "description": "The temperature rating of the material",
                    "type": "number"
                },
                "voltage": {
                    "description": "The voltage rating of the material",
                    "type": "number",
                    "exclusiveMinimum": 0
                }
            }
        }
    },
    "required": ["name", "dielectricStrength"],

    "$defs": {
        "dieletricStrengthPoint": {
            "description": "data for describing one point of dieletric strength",
            "type": "object",
            "properties": {
                "value": {
                    "description": "Dieletric strength value, in V / m",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "thickness": {
                    "description": "Thickness of the material",
                    "type": "number",
                    "exclusiveMinimum": 0
                },
                "humidity": {
                    "description": "Humidity for the field value, in proportion over 1",
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1
                }
            },
            "required": ["value"]
        }
    }
}

=== AlfVII/mal/samples/magnetic/insulation/material/kapton_hn.json
{
    "composition": "polyimide",
    "name": "Kapton HN",
    "manufacturer": "DuPont",
    "thermalConductivity": 0.2,
    "dielectricStrength": [
        {
            "value": 303e6,
            "thickness": 25e-6,
            "humidity": 0.5
        },
        {
            "value": 240e6,
            "thickness": 50e-6,
            "humidity": 0.5
        },
        {
            "value": 205e6,
            "thickness": 75e-6,
            "humidity": 0.5
        },
        {
            "value": 154e6,
            "thickness": 125e-6,
            "humidity": 0.5
        },
        {
            "value": 339e6,
            "thickness": 25e-6,
            "humidity": 0
        },
        {
            "value": 315e6,
            "thickness": 25e-6,
            "humidity": 0.3
        },
        {
            "value": 280e6,
            "thickness": 25e-6,
            "humidity": 0.8
        },
        {
            "value": 268e6,
            "thickness": 25e-6,
            "humidity": 1
        }
    ]
}
